### ISSUE TITLE
SyntaxError: Unexpected token >

### ISSUE THREAD

**Issue by scil** [rotorz/markdown-it-external-links#3]
I got this err:

```
/vagrant/www/node_modules/markdown-it-external-links/lib/index.js:17
      ? options.internalDomains.map(domain => domain.toLowerCase())
                                            ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at getParser (eval at <anonymous> (/vagrant/www/zc/free.js:11:52), <anonymous>:15:14)
    at Object.zc.editor.getMarkdownParser (eval at <anonymous> (/vagrant/www/zc/free.js:12:43), <anonymous>:256:38)
    at Object.<anonymous> (/vagrant/www/zc/free.js:38:28)
    at Module._compile (module.js:456:26)
```

I dont' know '=>' means  in js ?

**Comment by mvanduijker** [comment]
It's an [arrow function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions) You need ES6 for this package.

**Comment by kruncher** [comment]
Yes this is an ES6 package.
